a = input('Digite algo ')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'So tem espaços? {a.isspace()}')
print(f'É um numero? {a.isnumeric()}')
print(f'É alfabetico? {a.isalpha()}')
print(f'É alfanumerico? {a.isalnum()}')
print(f'Esta em maiusculas? {a.isupper()}')
print(f'Esta em minusculas? {a.islower()}')
print(f'Esta capitalizada, {a.istitle()}')
